"""add daily lock table

Revision ID: 1ef8fcb5fe63
Revises: cfaf901a6620
Create Date: 2026-01-12 20:12:22.208931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef8fcb5fe63'
down_revision: Union[str, Sequence[str], None] = 'cfaf901a6620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_lock',
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('service_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_lock')
    # ### end Alembic commands ###
